#!/usr/bin/env bash
if [ ! -f ~/tmp-gjs-documentation/index.html ]; then
  INDEX_HTML='<!DOCTYPE html>
<html>
  <head>
    <title>GJS Modules Documentation</title>
    <link rel="stylesheet" type="text/css" href="Gtk-3.0/C.css">
  </head>
  <body>
    <div class="page" role="main">
      <div class="body">
        <div class="hgroup">
          <h1 class="title"><span class="title">GJS Modules Documentation</span></h1>
        </div>
        <div class="region">
          <div class="contents">
            <div class="links topiclinks">
              <div class="inner">
                <div class="title title-links"><h2><span class="title">Folders</span></h2></div>
                <div class="region">
                  <ul>'
  for folder in `ls html`; do
    INDEX_HTML="${INDEX_HTML}
                      <li class='links'><a href='${folder}' title='${folder}'>${folder}</a></li>"
  done
  INDEX_HTML="${INDEX_HTML}
                  </ul>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class='clear'></div>
    </div>
  </body>
</html>"
  echo "$INDEX_HTML">~/tmp-gjs-documentation/index.html
fi